### ISSUE TITLE
[rosrun error]

### ISSUE THREAD

**Issue by chris-s907** [tuw-robotics/tuw_marker_slam#8]
Hi Markus :
When I ran the command ' rosrun tuw_marker_slam tuw_marker_slam_node' , I saw this problem in my teminal. Can you help me to solve it ? Thank you very much.
Problems are as follows:

[rosrun] Couldn't find executable named tuw_marker_slam_node below /catkin_ws/src/......./tuw_marker_filter/tuw_marker_slam

**Comment by maxbader** [comment]
Sorry, the pkg is currently unsupported and the information you provided is not enough to make an educated guess on the problem.
